apiVersion: v1
kind: Pod
metadata:
 name: mypod
spec:
 containers:
   - name: docker
     image: qnib/plain-dind:2019-01-30.1
     command:
       - dockerd
     securityContext:
     #  privileged: true
       capabilities:
         add:
           - SYS_MODULE
           - SYS_RAWIO
           - SYS_PACCT
           - SYS_ADMIN
           - SYS_NICE
           - SYS_RESOURCE
           - SYS_TTY_CONFIG
           - AUDIT_CONTROL
           - NET_ADMIN
           - IPC_LOCK
           - IPC_OWNER
     volumeMounts:
       - mountPath: /sys/fs/cgroup
         name: cgroup-vol
 volumes:
  - name: cgroup-vol
    hostPath:
      path: /sys/fs/cgroup
      type: Directory
